services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    networks: 
      - task-manager
  backend:
    build: backend
    ports:
      - "3000:3000"
    networks:
      - task-manager
networks:
  task-manager:
    driver: bridge
